<a href="https://colab.research.google.com/github/aditi-s-baghel/Data_Cleaning_assignment/blob/main/Pandas_Assignment_TechMart.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Assignment - TechMart Sales Dataset

Load `TechMart_Sales_300Rows.csv` and solve the following questions.

## Q1. Load the CSV file.

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('TechMart_Sales_300Rows.csv')
df

,Order_ID,Customer_Name,Product,Category,Brand,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode
0,ORD1001,Anjali Gupta,Laptop,Electronics,HP,32598,2,Pune,MH,27-01-2025,Cancelled,2.0,Poor Quality (Returned),UPI
1,ORD1002,Deepak Jain,Printer,Office,Canon,4405,1,Bhopal,MP,01-03-2025,Cancelled,2.0,Amazing (5 Stars),UPI
2,ORD1003,Harsh Agrawal,Mouse,Accessories,Logitech,29393,4,Jaipur,RJ,13-03-2025,Delivered,5.0,Average Quality (Late Delivery),Debit Card
3,ORD1004,Pooja Yadav,Monitor,Electronics,Dell,28721,3,Delhi,Delhi,24-01-2025,Pending,1.0,Good Product (Satisfied),Credit Card
4,ORD1005,Arjun Mehta,Smart Watch,Electronics,Apple,6195,4,Pune,MH,01-02-2025,Pending,5.0,Good Product (Satisfied),Net Banking
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,ORD1299,Harsh Agrawal,Keyboard,Accessories,Logitech,43227,2,Nagpur,MH,30-01-2025,Pending,4.0,Nice Product (Value for Money),Net Banking
299,ORD1300,Pooja Yadav,Smart Watch,Electronics,Apple,51951,5,Jaipur,RJ,31-03-2025,Pending,1.0,Nice Product (Value for Money),Net Banking
300,ORD1011,Simran Kaur,Keyboard,Accessories,Logitech,18801,2,Pune,MH,18-05-2025,Pending,5.0,Amazing (5 Stars),Debit Card
301,ORD1012,Deepak Jain,Printer,Office,Canon,29246,2,Nagpur,MH,07-05-2025,Delivered,5.0,Excellent Product (Fast Delivery),UPI
302,ORD1013,Rohit Patel,Keyboard,Accessories,Logitech,78672,1,Jaipur,RJ,08-04-2025,Cancelled,4.0,Nice Product (Value for Money),Net Banking

## Q2. Display first 10 rows.

In [2]:
df.head(10)

,Order_ID,Customer_Name,Product,Category,Brand,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode
0,ORD1001,Anjali Gupta,Laptop,Electronics,HP,32598,2,Pune,MH,27-01-2025,Cancelled,2.0,Poor Quality (Returned),UPI
1,ORD1002,Deepak Jain,Printer,Office,Canon,4405,1,Bhopal,MP,01-03-2025,Cancelled,2.0,Amazing (5 Stars),UPI
2,ORD1003,Harsh Agrawal,Mouse,Accessories,Logitech,29393,4,Jaipur,RJ,13-03-2025,Delivered,5.0,Average Quality (Late Delivery),Debit Card
3,ORD1004,Pooja Yadav,Monitor,Electronics,Dell,28721,3,Delhi,Delhi,24-01-2025,Pending,1.0,Good Product (Satisfied),Credit Card
4,ORD1005,Arjun Mehta,Smart Watch,Electronics,Apple,6195,4,Pune,MH,01-02-2025,Pending,5.0,Good Product (Satisfied),Net Banking
5,ORD1006,Vivek Joshi,Smart Watch,Electronics,Apple,76174,2,Nagpur,MH,12-01-2025,Cancelled,1.0,Very Nice (Recommended),Credit Card
6,ORD1007,Priya Singh,Mouse,Accessories,Logitech,50323,3,Indore,MP,12-06-2025,Pending,4.0,Average Quality (Late Delivery),Credit Card
7,ORD1008,Arjun Mehta,Mouse,Accessories,Logitech,9858,5,Pune,MH,17-05-2025,Cancelled,2.0,Very Nice (Recommended),Cash
8,ORD1009,Simran Kaur,Printer,Office,Canon,73500,2,Pune,MH,15-01-2025,Delivered,3.0,Excellent Product (Fast Delivery),Credit Card
9,ORD1010,Neha Soni,Monitor,Electronics,Dell,28153,5,Indore,MP,24-02-2025,Cancelled,3.0,Nice Product (Value for Money),Debit Card

## Q3. Display last 5 rows.

In [3]:
df.tail(5)

,Order_ID,Customer_Name,Product,Category,Brand,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode
298,ORD1299,Harsh Agrawal,Keyboard,Accessories,Logitech,43227,2,Nagpur,MH,30-01-2025,Pending,4.0,Nice Product (Value for Money),Net Banking
299,ORD1300,Pooja Yadav,Smart Watch,Electronics,Apple,51951,5,Jaipur,RJ,31-03-2025,Pending,1.0,Nice Product (Value for Money),Net Banking
300,ORD1011,Simran Kaur,Keyboard,Accessories,Logitech,18801,2,Pune,MH,18-05-2025,Pending,5.0,Amazing (5 Stars),Debit Card
301,ORD1012,Deepak Jain,Printer,Office,Canon,29246,2,Nagpur,MH,07-05-2025,Delivered,5.0,Excellent Product (Fast Delivery),UPI
302,ORD1013,Rohit Patel,Keyboard,Accessories,Logitech,78672,1,Jaipur,RJ,08-04-2025,Cancelled,4.0,Nice Product (Value for Money),Net Banking

## Q4. Check shape, columns and data types.

In [4]:
df.shape

(303, 14)

In [5]:
df.columns

Index(['Order_ID', 'Customer_Name', 'Product', 'Category', 'Brand', 'Price',
       'Quantity', 'City', 'State', 'Order_Date', 'Delivery_Status', 'Rating',
       'Review', 'Payment_Mode'],
      dtype='object')

In [6]:
df.dtypes

Order_ID            object
Customer_Name       object
Product             object
Category            object
Brand               object
Price                int64
Quantity             int64
City                object
State               object
Order_Date          object
Delivery_Status     object
Rating             float64
Review              object
Payment_Mode        object
dtype: object

## Q5. Find null values.

In [7]:
df.isnull().sum()

Order_ID           0
Customer_Name      0
Product            0
Category           0
Brand              0
Price              0
Quantity           0
City               0
State              0
Order_Date         0
Delivery_Status    0
Rating             5
Review             0
Payment_Mode       0
dtype: int64

## Q6. Fill missing Rating with 0.

In [8]:
df['Rating']= df['Rating'].replace(np.nan,0)
df['Rating']

0      2.0
1      2.0
2      5.0
3      1.0
4      5.0
      ...
298    4.0
299    1.0
300    5.0
301    5.0
302    4.0
Name: Rating, Length: 303, dtype: float64

## Q7. Rename `Customer_Name` to `Customer`.

In [9]:
df = df.rename(columns={'Customer_Name':'Customer'})
df

,Order_ID,Customer,Product,Category,Brand,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode
0,ORD1001,Anjali Gupta,Laptop,Electronics,HP,32598,2,Pune,MH,27-01-2025,Cancelled,2.0,Poor Quality (Returned),UPI
1,ORD1002,Deepak Jain,Printer,Office,Canon,4405,1,Bhopal,MP,01-03-2025,Cancelled,2.0,Amazing (5 Stars),UPI
2,ORD1003,Harsh Agrawal,Mouse,Accessories,Logitech,29393,4,Jaipur,RJ,13-03-2025,Delivered,5.0,Average Quality (Late Delivery),Debit Card
3,ORD1004,Pooja Yadav,Monitor,Electronics,Dell,28721,3,Delhi,Delhi,24-01-2025,Pending,1.0,Good Product (Satisfied),Credit Card
4,ORD1005,Arjun Mehta,Smart Watch,Electronics,Apple,6195,4,Pune,MH,01-02-2025,Pending,5.0,Good Product (Satisfied),Net Banking
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,ORD1299,Harsh Agrawal,Keyboard,Accessories,Logitech,43227,2,Nagpur,MH,30-01-2025,Pending,4.0,Nice Product (Value for Money),Net Banking
299,ORD1300,Pooja Yadav,Smart Watch,Electronics,Apple,51951,5,Jaipur,RJ,31-03-2025,Pending,1.0,Nice Product (Value for Money),Net Banking
300,ORD1011,Simran Kaur,Keyboard,Accessories,Logitech,18801,2,Pune,MH,18-05-2025,Pending,5.0,Amazing (5 Stars),Debit Card
301,ORD1012,Deepak Jain,Printer,Office,Canon,29246,2,Nagpur,MH,07-05-2025,Delivered,5.0,Excellent Product (Fast Delivery),UPI
302,ORD1013,Rohit Patel,Keyboard,Accessories,Logitech,78672,1,Jaipur,RJ,08-04-2025,Cancelled,4.0,Nice Product (Value for Money),Net Banking

## Q8. Delete `Brand` column.

In [10]:
df.drop('Brand',axis=1)

,Order_ID,Customer,Product,Category,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode
0,ORD1001,Anjali Gupta,Laptop,Electronics,32598,2,Pune,MH,27-01-2025,Cancelled,2.0,Poor Quality (Returned),UPI
1,ORD1002,Deepak Jain,Printer,Office,4405,1,Bhopal,MP,01-03-2025,Cancelled,2.0,Amazing (5 Stars),UPI
2,ORD1003,Harsh Agrawal,Mouse,Accessories,29393,4,Jaipur,RJ,13-03-2025,Delivered,5.0,Average Quality (Late Delivery),Debit Card
3,ORD1004,Pooja Yadav,Monitor,Electronics,28721,3,Delhi,Delhi,24-01-2025,Pending,1.0,Good Product (Satisfied),Credit Card
4,ORD1005,Arjun Mehta,Smart Watch,Electronics,6195,4,Pune,MH,01-02-2025,Pending,5.0,Good Product (Satisfied),Net Banking
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,ORD1299,Harsh Agrawal,Keyboard,Accessories,43227,2,Nagpur,MH,30-01-2025,Pending,4.0,Nice Product (Value for Money),Net Banking
299,ORD1300,Pooja Yadav,Smart Watch,Electronics,51951,5,Jaipur,RJ,31-03-2025,Pending,1.0,Nice Product (Value for Money),Net Banking
300,ORD1011,Simran Kaur,Keyboard,Accessories,18801,2,Pune,MH,18-05-2025,Pending,5.0,Amazing (5 Stars),Debit Card
301,ORD1012,Deepak Jain,Printer,Office,29246,2,Nagpur,MH,07-05-2025,Delivered,5.0,Excellent Product (Fast Delivery),UPI
302,ORD1013,Rohit Patel,Keyboard,Accessories,78672,1,Jaipur,RJ,08-04-2025,Cancelled,4.0,Nice Product (Value for Money),Net Banking

## Q9. Create `Total_Amount = Price * Quantity`.

In [11]:
df['Total_Amount'] = df['Price'] * df['Quantity']
df['Total_Amount']

0       65196
1        4405
2      117572
3       86163
4       24780
        ...
298     86454
299    259755
300     37602
301     58492
302     78672
Name: Total_Amount, Length: 303, dtype: int64

## Q10. Display only Customer, Product and Total_Amount.

In [12]:
df[['Customer','Product','Total_Amount']]

             Customer      Product  Total_Amount
0      Anjali Gupta         Laptop         65196
1         Deepak Jain      Printer          4405
2       Harsh Agrawal        Mouse        117572
3         Pooja Yadav      Monitor         86163
4         Arjun Mehta  Smart Watch         24780
..                ...          ...           ...
298     Harsh Agrawal     Keyboard         86454
299     Pooja Yadav    Smart Watch        259755
300       Simran Kaur     Keyboard         37602
301       Deepak Jain      Printer         58492
302       Rohit Patel     Keyboard         78672

[303 rows x 3 columns]

## Q11. Show Delivered orders.

In [13]:
df[df['Delivery_Status']=='Delivered']

,Order_ID,Customer,Product,Category,Brand,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
2,ORD1003,Harsh Agrawal,Mouse,Accessories,Logitech,29393,4,Jaipur,RJ,13-03-2025,Delivered,5.0,Average Quality (Late Delivery),Debit Card,117572
8,ORD1009,Simran Kaur,Printer,Office,Canon,73500,2,Pune,MH,15-01-2025,Delivered,3.0,Excellent Product (Fast Delivery),Credit Card,147000
11,ORD1012,Deepak Jain,Printer,Office,Canon,29246,2,Nagpur,MH,07-05-2025,Delivered,5.0,Excellent Product (Fast Delivery),UPI,58492
16,ORD1017,Sakshi Sharma,Tablet,Electronics,Apple,3052,1,Hyderabad,TS,20-03-2025,Delivered,3.0,Excellent Product (Fast Delivery),Cash,3052
17,ORD1018,Deepak Jain,Mobile,Electronics,Samsung,64199,1,Indore,MP,02-02-2025,Delivered,5.0,Nice Product (Value for Money),Net Banking,64199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,ORD1293,Rohit Patel,Tablet,Electronics,Apple,63777,1,Bhopal,MP,17-04-2025,Delivered,3.0,Good Product (Satisfied),Cash,63777
294,ORD1295,Simran Kaur,Speaker,Accessories,Boat,9304,3,Nagpur,MH,30-01-2025,Delivered,1.0,Bad Packaging (Delayed),UPI,27912
296,ORD1297,Neha Soni,Keyboard,Accessories,Logitech,57140,4,Delhi,Delhi,07-06-2025,Delivered,1.0,Nice Product (Value for Money),Net Banking,228560
297,ORD1298,Mohit Gupta,Printer,Office,Canon,28653,2,Bhopal,MP,30-06-2025,Delivered,3.0,Amazing (5 Stars),UPI,57306
301,ORD1012,Deepak Jain,Printer,Office,Canon,29246,2,Nagpur,MH,07-05-2025,Delivered,5.0,Excellent Product (Fast Delivery),UPI,58492

## Q12. Show products with Price > 50000.

In [14]:
df[df['Price']>50000]

,Order_ID,Customer,Product,Category,Brand,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
5,ORD1006,Vivek Joshi,Smart Watch,Electronics,Apple,76174,2,Nagpur,MH,12-01-2025,Cancelled,1.0,Very Nice (Recommended),Credit Card,152348
6,ORD1007,Priya Singh,Mouse,Accessories,Logitech,50323,3,Indore,MP,12-06-2025,Pending,4.0,Average Quality (Late Delivery),Credit Card,150969
8,ORD1009,Simran Kaur,Printer,Office,Canon,73500,2,Pune,MH,15-01-2025,Delivered,3.0,Excellent Product (Fast Delivery),Credit Card,147000
12,ORD1013,Rohit Patel,Keyboard,Accessories,Logitech,78672,1,Jaipur,RJ,08-04-2025,Cancelled,4.0,Nice Product (Value for Money),Net Banking,78672
17,ORD1018,Deepak Jain,Mobile,Electronics,Samsung,64199,1,Indore,MP,02-02-2025,Delivered,5.0,Nice Product (Value for Money),Net Banking,64199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293,ORD1294,Arjun Mehta,Monitor,Electronics,Dell,60181,2,Nagpur,MH,04-05-2025,Pending,5.0,Nice Product (Value for Money),UPI,120362
295,ORD1296,Sneha Jain,Mouse,Accessories,Logitech,72839,2,Delhi,Delhi,24-05-2025,Pending,3.0,Nice Product (Value for Money),Cash,145678
296,ORD1297,Neha Soni,Keyboard,Accessories,Logitech,57140,4,Delhi,Delhi,07-06-2025,Delivered,1.0,Nice Product (Value for Money),Net Banking,228560
299,ORD1300,Pooja Yadav,Smart Watch,Electronics,Apple,51951,5,Jaipur,RJ,31-03-2025,Pending,1.0,Nice Product (Value for Money),Net Banking,259755
302,ORD1013,Rohit Patel,Keyboard,Accessories,Logitech,78672,1,Jaipur,RJ,08-04-2025,Cancelled,4.0,Nice Product (Value for Money),Net Banking,78672

## Q13. Show customers from Bhopal.

In [15]:
df[df['City']=="Bhopal"]

,Order_ID,Customer,Product,Category,Brand,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
1,ORD1002,Deepak Jain,Printer,Office,Canon,4405,1,Bhopal,MP,01-03-2025,Cancelled,2.0,Amazing (5 Stars),UPI,4405
13,ORD1014,Nikita Rao,Headphone,Accessories,Sony,15514,5,Bhopal,MP,14-06-2025,Pending,3.0,Good Product (Satisfied),Credit Card,77570
43,ORD1044,Karan Shah,Mouse,Accessories,Logitech,25813,4,Bhopal,MP,13-03-2025,Delivered,3.0,Worth Buying (Happy Customer),Credit Card,103252
61,ORD1062,Mohit Gupta,Speaker,Accessories,Boat,51468,3,Bhopal,MP,12-02-2025,Pending,4.0,Average Quality (Late Delivery),Net Banking,154404
63,ORD1064,Simran Kaur,Keyboard,Accessories,Logitech,34599,4,Bhopal,MP,24-02-2025,Pending,3.0,Bad Packaging (Delayed),Credit Card,138396
70,ORD1071,Riya Tiwari,Tablet,Electronics,Apple,55557,4,Bhopal,MP,21-04-2025,Pending,1.0,Nice Product (Value for Money),Cash,222228
92,ORD1093,Nikita Rao,Smart Watch,Electronics,Apple,23462,4,Bhopal,MP,16-06-2025,Pending,5.0,Worth Buying (Happy Customer),Cash,93848
98,ORD1099,Sneha Jain,Monitor,Electronics,Dell,72884,4,Bhopal,MP,27-02-2025,Delivered,1.0,Nice Product (Value for Money),UPI,291536
111,ORD1112,Simran Kaur,Monitor,Electronics,Dell,61481,3,Bhopal,MP,10-02-2025,Delivered,5.0,Nice Product (Value for Money),Credit Card,184443
114,ORD1115,Rahul Sharma,Smart Watch,Electronics,Apple,79982,4,Bhopal,MP,28-02-2025,Cancelled,3.0,Bad Packaging (Delayed),Cash,319928
120,ORD1121,Karan Shah,Speaker,Accessories,Boat,74084,3,Bhopal,MP,26-02-2025,Cancelled,5.0,Good Product (Satisfied),Debit Card,222252
140,ORD1141,Sakshi Sharma,Headphone,Accessories,Sony,35554,1,Bhopal,MP,11-03-2025,Cancelled,2.0,Worth Buying (Happy Customer),Credit Card,35554
146,ORD1147,Neha Soni,Smart Watch,Electronics,Apple,1507,2,Bhopal,MP,24-02-2025,Delivered,3.0,Worth Buying (Happy Customer),Credit Card,3014
147,ORD1148,Pooja Yadav,Mobile,Electronics,Samsung,65693,4,Bhopal,MP,03-02-2025,Pending,2.0,Poor Quality (Returned),Cash,262772
155,ORD1156,Nikita Rao,Smart Watch,Electronics,Apple,46629,5,Bhopal,MP,21-03-2025,Pending,1.0,Nice Product (Value for Money),UPI,233145
157,ORD1158,Deepak Jain,Headphone,Accessories,Sony,59447,5,Bhopal,MP,24-03-2025,Cancelled,2.0,Nice Product (Value for Money),Net Banking,297235
165,ORD1166,Harsh Agrawal,Headphone,Accessories,Sony,44640,5,Bhopal,MP,02-06-2025,Pending,2.0,Average Quality (Late Delivery),Cash,223200
171,ORD1172,Simran Kaur,Tablet,Electronics,Apple,54881,1,Bhopal,MP,09-05-2025,Pending,4.0,Very Nice (Recommended),Debit Card,54881
175,ORD1176,Vivek Joshi,Mobile,Electronics,Samsung,31752,4,Bhopal,MP,28-04-2025,Delivered,5.0,Good Product (Satisfied),Debit Card,127008
176,ORD1177,Sakshi Sharma,Headphone,Accessories,Sony,68051,5,Bhopal,MP,06-02-2025,Pending,2.0,Excellent (Must Buy),UPI,340255
178,ORD1179,Arjun Mehta,Mobile,Electronics,Samsung,51677,4,Bhopal,MP,12-06-2025,Pending,1.0,Bad Packaging (Delayed),Credit Card,206708
215,ORD1216,Vivek Joshi,Speaker,Accessories,Boat,48781,3,Bhopal,MP,17-04-2025,Cancelled,1.0,Worth Buying (Happy Customer),UPI,146343
219,ORD1220,Sakshi Sharma,Speaker,Accessories,Boat,18598,5,Bhopal,MP,24-05-2025,Pending,2.0,Nice Product (Value for Money),Net Banking,92990
228,ORD1229,Karan Shah,Headphone,Accessories,Sony,23446,4,Bhopal,MP,10-01-2025,Pending,2.0,Nice Product (Value for Money),Cash,93784
229,ORD1230,Vivek Joshi,Laptop,Electronics,HP,39610,5,Bhopal,MP,28-01-2025,Pending,5.0,Worth Buying (Happy Customer),Debit Card,198050
234,ORD1235,Pooja Yadav,Monitor,Electronics,Dell,34782,3,Bhopal,MP,16-01-2025,Cancelled,2.0,Good Product (Satisfied),Debit Card,104346
242,ORD1243,Arjun Mehta,Mobile,Electronics,Samsung,9546,4,Bhopal,MP,15-03-2025,Pending,1.0,Average Quality (Late Delivery),Cash,38184
251,ORD1252,Harsh Agrawal,Speaker,Accessories,Boat,45643,4,Bhopal,MP,23-03-2025,Cancelled,5.0,Excellent (Must Buy),Debit Card,182572
255,ORD1256,Nikita Rao,Printer,Office,Canon,10039,2,Bhopal,MP,21-06-2025,Cancelled,5.0,Very Nice (Recommended),Debit Card,20078
273,ORD1274,Riya Tiwari,Tablet,Electronics,Apple,13303,4,Bhopal,MP,20-01-2025,Pending,2.0,Amazing (5 Stars),Net Banking,53212
292,ORD1293,Rohit Patel,Tablet,Electronics,Apple,63777,1,Bhopal,MP,17-04-2025,Delivered,3.0,Good Product (Satisfied),Cash,63777
297,ORD1298,Mohit Gupta,Printer,Office,Canon,28653,2,Bhopal,MP,30-06-2025,Delivered,3.0,Amazing (5 Stars),UPI,57306

## Q14. Show Rating >= 4.

In [16]:
df[df['Rating']>=4]

,Order_ID,Customer,Product,Category,Brand,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
2,ORD1003,Harsh Agrawal,Mouse,Accessories,Logitech,29393,4,Jaipur,RJ,13-03-2025,Delivered,5.0,Average Quality (Late Delivery),Debit Card,117572
4,ORD1005,Arjun Mehta,Smart Watch,Electronics,Apple,6195,4,Pune,MH,01-02-2025,Pending,5.0,Good Product (Satisfied),Net Banking,24780
6,ORD1007,Priya Singh,Mouse,Accessories,Logitech,50323,3,Indore,MP,12-06-2025,Pending,4.0,Average Quality (Late Delivery),Credit Card,150969
10,ORD1011,Simran Kaur,Keyboard,Accessories,Logitech,18801,2,Pune,MH,18-05-2025,Pending,5.0,Amazing (5 Stars),Debit Card,37602
11,ORD1012,Deepak Jain,Printer,Office,Canon,29246,2,Nagpur,MH,07-05-2025,Delivered,5.0,Excellent Product (Fast Delivery),UPI,58492
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293,ORD1294,Arjun Mehta,Monitor,Electronics,Dell,60181,2,Nagpur,MH,04-05-2025,Pending,5.0,Nice Product (Value for Money),UPI,120362
298,ORD1299,Harsh Agrawal,Keyboard,Accessories,Logitech,43227,2,Nagpur,MH,30-01-2025,Pending,4.0,Nice Product (Value for Money),Net Banking,86454
300,ORD1011,Simran Kaur,Keyboard,Accessories,Logitech,18801,2,Pune,MH,18-05-2025,Pending,5.0,Amazing (5 Stars),Debit Card,37602
301,ORD1012,Deepak Jain,Printer,Office,Canon,29246,2,Nagpur,MH,07-05-2025,Delivered,5.0,Excellent Product (Fast Delivery),UPI,58492
302,ORD1013,Rohit Patel,Keyboard,Accessories,Logitech,78672,1,Jaipur,RJ,08-04-2025,Cancelled,4.0,Nice Product (Value for Money),Net Banking,78672

## Q15. Show Electronics category.

In [17]:
df[df['Category']=='Electronics']

,Order_ID,Customer,Product,Category,Brand,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
0,ORD1001,Anjali Gupta,Laptop,Electronics,HP,32598,2,Pune,MH,27-01-2025,Cancelled,2.0,Poor Quality (Returned),UPI,65196
3,ORD1004,Pooja Yadav,Monitor,Electronics,Dell,28721,3,Delhi,Delhi,24-01-2025,Pending,1.0,Good Product (Satisfied),Credit Card,86163
4,ORD1005,Arjun Mehta,Smart Watch,Electronics,Apple,6195,4,Pune,MH,01-02-2025,Pending,5.0,Good Product (Satisfied),Net Banking,24780
5,ORD1006,Vivek Joshi,Smart Watch,Electronics,Apple,76174,2,Nagpur,MH,12-01-2025,Cancelled,1.0,Very Nice (Recommended),Credit Card,152348
9,ORD1010,Neha Soni,Monitor,Electronics,Dell,28153,5,Indore,MP,24-02-2025,Cancelled,3.0,Nice Product (Value for Money),Debit Card,140765
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,ORD1285,Vivek Joshi,Tablet,Electronics,Apple,63284,3,Mumbai,MH,12-04-2025,Pending,2.0,Worth Buying (Happy Customer),Debit Card,189852
289,ORD1290,Aman Verma,Tablet,Electronics,Apple,14835,2,Indore,MP,12-02-2025,Cancelled,3.0,Amazing (5 Stars),UPI,29670
292,ORD1293,Rohit Patel,Tablet,Electronics,Apple,63777,1,Bhopal,MP,17-04-2025,Delivered,3.0,Good Product (Satisfied),Cash,63777
293,ORD1294,Arjun Mehta,Monitor,Electronics,Dell,60181,2,Nagpur,MH,04-05-2025,Pending,5.0,Nice Product (Value for Money),UPI,120362
299,ORD1300,Pooja Yadav,Smart Watch,Electronics,Apple,51951,5,Jaipur,RJ,31-03-2025,Pending,1.0,Nice Product (Value for Money),Net Banking,259755

## Q16. Sort by Price (Ascending).

In [18]:
df['Price'].sort_values()

101      836
14       925
20      1442
146     1507
279     2117
       ...
302    78672
160    78866
161    79497
213    79963
114    79982
Name: Price, Length: 303, dtype: int64

## Q17. Sort by Total_Amount (Descending).

In [19]:
df['Total_Amount'].sort_values(ascending=False)

213    399815
282    391655
62     390400
216    381605
249    380950
        ...
16       3052
146      3014
14       2775
101      2508
20       1442
Name: Total_Amount, Length: 303, dtype: int64

## Q18. Sort by City then Price.

In [20]:
df['City'].sort_values()

157    Bhopal
111    Bhopal
98     Bhopal
273    Bhopal
215    Bhopal
        ...
90       Pune
91       Pune
216      Pune
99       Pune
0        Pune
Name: City, Length: 303, dtype: object

## Q19. Convert Customer to uppercase.

In [21]:
df['Customer'].str.upper()

0        ANJALI GUPTA
1           DEEPAK JAIN
2         HARSH AGRAWAL
3           POOJA YADAV
4           ARJUN MEHTA
             ...
298       HARSH AGRAWAL
299       POOJA YADAV
300         SIMRAN KAUR
301         DEEPAK JAIN
302         ROHIT PATEL
Name: Customer, Length: 303, dtype: object

## Q20. Convert Product to lowercase.

In [22]:
df['Product'].str.lower()

0           laptop
1          printer
2            mouse
3          monitor
4      smart watch
          ...
298       keyboard
299    smart watch
300       keyboard
301        printer
302       keyboard
Name: Product, Length: 303, dtype: object

## Q21. Remove everything after '(' from Review.

In [23]:
value = "Good Product (Satisfied)"
value = value.split('(') #ek particular symbol se divide ya split kr deta hai
value[0].strip() #Extra spaces unhe remove

'Good Product'

## Q22. Find customers whose names start with 'A'.

In [24]:
df[df['Customer'].str.startswith('A')]

,Order_ID,Customer,Product,Category,Brand,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
4,ORD1005,Arjun Mehta,Smart Watch,Electronics,Apple,6195,4,Pune,MH,01-02-2025,Pending,5.0,Good Product (Satisfied),Net Banking,24780
7,ORD1008,Arjun Mehta,Mouse,Accessories,Logitech,9858,5,Pune,MH,17-05-2025,Cancelled,2.0,Very Nice (Recommended),Cash,49290
22,ORD1023,Akash Dubey,Mouse,Accessories,Logitech,53854,2,Hyderabad,TS,25-01-2025,Cancelled,1.0,Excellent (Must Buy),Credit Card,107708
29,ORD1030,Aman Verma,Smart Watch,Electronics,Apple,66409,5,Hyderabad,TS,15-01-2025,Cancelled,2.0,Good Product (Satisfied),Cash,332045
31,ORD1032,Aman Verma,Smart Watch,Electronics,Apple,55448,5,Indore,MP,14-05-2025,Pending,5.0,Worth Buying (Happy Customer),Cash,277240
39,ORD1040,Aman Verma,Tablet,Electronics,Apple,56833,2,Delhi,Delhi,20-03-2025,Pending,1.0,Excellent Product (Fast Delivery),Credit Card,113666
40,ORD1041,Aditi Mishra,Mouse,Accessories,Logitech,46857,5,Indore,MP,08-06-2025,Cancelled,4.0,Average Quality (Late Delivery),Cash,234285
45,ORD1046,Anjali Gupta,Smart Watch,Electronics,Apple,45809,3,Jaipur,RJ,05-06-2025,Cancelled,4.0,Good Product (Satisfied),Debit Card,137427
52,ORD1053,Aman Verma,Mouse,Accessories,Logitech,10045,4,Hyderabad,TS,11-06-2025,Cancelled,4.0,Very Nice (Recommended),Debit Card,40180
53,ORD1054,Akash Dubey,Printer,Office,Canon,19842,1,Mumbai,MH,19-04-2025,Delivered,1.0,Average Quality (Late Delivery),Net Banking,19842
59,ORD1060,Aditi Mishra,Printer,Office,Canon,77056,1,Jaipur,RJ,08-04-2025,Pending,5.0,Excellent Product (Fast Delivery),Credit Card,77056
65,ORD1066,Arjun Mehta,Mouse,Accessories,Logitech,5776,1,Indore,MP,21-02-2025,Delivered,2.0,Amazing (5 Stars),Cash,5776
75,ORD1076,Akash Dubey,Headphone,Accessories,Sony,62902,4,Mumbai,MH,05-01-2025,Delivered,4.0,Worth Buying (Happy Customer),Cash,251608
81,ORD1082,Anjali Gupta,Laptop,Electronics,HP,62024,4,Pune,MH,29-03-2025,Delivered,4.0,Excellent Product (Fast Delivery),Credit Card,248096
82,ORD1083,Akash Dubey,Mobile,Electronics,Samsung,53021,4,Indore,MP,28-05-2025,Cancelled,1.0,Excellent Product (Fast Delivery),Cash,212084
97,ORD1098,Aditi Mishra,Monitor,Electronics,Dell,38252,4,Delhi,Delhi,01-02-2025,Delivered,4.0,Amazing (5 Stars),Cash,153008
103,ORD1104,Aditi Mishra,Mouse,Accessories,Logitech,31113,4,Jaipur,RJ,23-03-2025,Cancelled,1.0,Nice Product (Value for Money),Debit Card,124452
105,ORD1106,Anjali Gupta,Headphone,Accessories,Sony,2511,2,Hyderabad,TS,17-06-2025,Delivered,4.0,Good Product (Satisfied),Debit Card,5022
107,ORD1108,Aman Verma,Smart Watch,Electronics,Apple,31271,3,Indore,MP,24-01-2025,Pending,2.0,Good Product (Satisfied),UPI,93813
116,ORD1117,Arjun Mehta,Keyboard,Accessories,Logitech,39180,3,Indore,MP,14-02-2025,Delivered,4.0,Average Quality (Late Delivery),Net Banking,117540
117,ORD1118,Arjun Mehta,Headphone,Accessories,Sony,22067,3,Pune,MH,17-03-2025,Cancelled,4.0,Bad Packaging (Delayed),UPI,66201
122,ORD1123,Anjali Gupta,Mouse,Accessories,Logitech,51440,4,Delhi,Delhi,21-06-2025,Cancelled,3.0,Poor Quality (Returned),Debit Card,205760
124,ORD1125,Aditi Mishra,Speaker,Accessories,Boat,31447,3,Hyderabad,TS,25-06-2025,Pending,1.0,Poor Quality (Returned),Credit Card,94341
125,ORD1126,Aman Verma,Printer,Office,Canon,25378,1,Pune,MH,24-01-2025,Cancelled,4.0,Very Nice (Recommended),Net Banking,25378
130,ORD1131,Akash Dubey,Speaker,Accessories,Boat,67771,5,Nagpur,MH,26-04-2025,Cancelled,1.0,Very Nice (Recommended),Net Banking,338855
131,ORD1132,Aman Verma,Headphone,Accessories,Sony,60536,1,Pune,MH,03-05-2025,Pending,1.0,Excellent (Must Buy),UPI,60536
132,ORD1133,Akash Dubey,Speaker,Accessories,Boat,11089,3,Indore,MP,07-02-2025,Delivered,5.0,Average Quality (Late Delivery),Credit Card,33267
139,ORD1140,Anjali Gupta,Tablet,Electronics,Apple,15558,3,Nagpur,MH,27-02-2025,Pending,5.0,Poor Quality (Returned),Net Banking,46674
141,ORD1142,Arjun Mehta,Laptop,Electronics,HP,19276,5,Delhi,Delhi,18-01-2025,Delivered,4.0,Excellent Product (Fast Delivery),UPI,96380
153,ORD1154,Aditi Mishra,Keyboard,Accessories,Logitech,10376,2,Delhi,Delhi,29-04-2025,Cancelled,4.0,Amazing (5 Stars),Debit Card,20752
156,ORD1157,Aman Verma,Tablet,Electronics,Apple,10557,1,Pune,MH,02-06-2025,Cancelled,5.0,Excellent (Must Buy),Debit Card,10557
173,ORD1174,Aman Verma,Monitor,Electronics,Dell,18691,4,Hyderabad,TS,07-06-2025,Delivered,4.0,Good Product (Satisfied),UPI,74764
178,ORD1179,Arjun Mehta,Mobile,Electronics,Samsung,51677,4,Bhopal,MP,12-06-2025,Pending,1.0,Bad Packaging (Delayed),Credit Card,206708
180,ORD1181,Aman Verma,Tablet,Electronics,Apple,23449,4,Nagpur,MH,11-06-2025,Delivered,4.0,Average Quality (Late Delivery),UPI,93796
191,ORD1192,Anjali Gupta,Monitor,Electronics,Dell,58993,2,Pune,MH,15-03-2025,Cancelled,5.0,Nice Product (Value for Money),Cash,117986
192,ORD1193,Anjali Gupta,Keyboard,Accessories,Logitech,59750,2,Indore,MP,23-01-2025,Cancelled,4.0,Bad Packaging (Delayed),Credit Card,119500
194,ORD1195,Aditi Mishra,Keyboard,Accessories,Logitech,65252,1,Mumbai,MH,22-05-2025,Cancelled,3.0,Bad Packaging (Delayed),Debit Card,65252
199,ORD1200,Aditi Mishra,Headphone,Accessories,Sony,16906,3,Pune,MH,07-06-2025,Cancelled,0.0,Good Product (Satisfied),Net Banking,50718
221,ORD1222,Akash Dubey,Mouse,Accessories,Logitech,37069,5,Mumbai,MH,27-02-2025,Pending,3.0,Worth Buying (Happy Customer),Cash,185345
222,ORD1223,Akash Dubey,Tablet,Electronics,Apple,46218,5,Hyderabad,TS,15-03-2025,Delivered,3.0,Amazing (5 Stars),Net Banking,231090
225,ORD1226,Anjali Gupta,Smart Watch,Electronics,Apple,32279,1,Mumbai,MH,27-02-2025,Cancelled,5.0,Very Nice (Recommended),UPI,32279
226,ORD1227,Anjali Gupta,Printer,Office,Canon,62418,1,Nagpur,MH,02-01-2025,Cancelled,2.0,Average Quality (Late Delivery),Debit Card,62418
227,ORD1228,Akash Dubey,Speaker,Accessories,Boat,38149,3,Mumbai,MH,15-06-2025,Delivered,3.0,Good Product (Satisfied),Net Banking,114447
237,ORD1238,Akash Dubey,Headphone,Accessories,Sony,32935,5,Mumbai,MH,15-05-2025,Pending,1.0,Poor Quality (Returned),Credit Card,164675
240,ORD1241,Aman Verma,Speaker,Accessories,Boat,67772,4,Delhi,Delhi,25-05-2025,Delivered,4.0,Poor Quality (Returned),Debit Card,271088
242,ORD1243,Arjun Mehta,Mobile,Electronics,Samsung,9546,4,Bhopal,MP,15-03-2025,Pending,1.0,Average Quality (Late Delivery),Cash,38184
244,ORD1245,Arjun Mehta,Mobile,Electronics,Samsung,70919,4,Delhi,Delhi,02-02-2025,Cancelled,5.0,Very Nice (Recommended),UPI,283676
246,ORD1247,Arjun Mehta,Keyboard,Accessories,Logitech,25204,1,Pune,MH,19-06-2025,Pending,1.0,Amazing (5 Stars),UPI,25204
248,ORD1249,Aman Verma,Printer,Office,Canon,31215,5,Hyderabad,TS,15-01-2025,Delivered,2.0,Poor Quality (Returned),Credit Card,156075
254,ORD1255,Aditi Mishra,Tablet,Electronics,Apple,59454,3,Indore,MP,18-05-2025,Cancelled,1.0,Very Nice (Recommended),UPI,178362
256,ORD1257,Aditi Mishra,Tablet,Electronics,Apple,2509,2,Pune,MH,31-01-2025,Cancelled,2.0,Nice Product (Value for Money),Cash,5018
258,ORD1259,Arjun Mehta,Monitor,Electronics,Dell,47639,5,Pune,MH,30-04-2025,Delivered,4.0,Nice Product (Value for Money),Credit Card,238195
259,ORD1260,Aditi Mishra,Tablet,Electronics,Apple,54754,1,Nagpur,MH,26-02-2025,Cancelled,5.0,Average Quality (Late Delivery),UPI,54754
264,ORD1265,Arjun Mehta,Laptop,Electronics,HP,64444,1,Hyderabad,TS,17-05-2025,Cancelled,1.0,Excellent (Must Buy),UPI,64444
266,ORD1267,Anjali Gupta,Mobile,Electronics,Samsung,32084,2,Delhi,Delhi,15-05-2025,Pending,5.0,Bad Packaging (Delayed),Credit Card,64168
270,ORD1271,Aditi Mishra,Smart Watch,Electronics,Apple,36032,1,Hyderabad,TS,25-06-2025,Pending,1.0,Poor Quality (Returned),Net Banking,36032
271,ORD1272,Aman Verma,Keyboard,Accessories,Logitech,2552,2,Nagpur,MH,06-02-2025,Cancelled,5.0,Excellent (Must Buy),UPI,5104
289,ORD1290,Aman Verma,Tablet,Electronics,Apple,14835,2,Indore,MP,12-02-2025,Cancelled,3.0,Amazing (5 Stars),UPI,29670
293,ORD1294,Arjun Mehta,Monitor,Electronics,Dell,60181,2,Nagpur,MH,04-05-2025,Pending,5.0,Nice Product (Value for Money),UPI,120362

## Q23. Find reviews containing 'Good'.

In [25]:
df[df['Review'].str.contains('Good')]

,Order_ID,Customer,Product,Category,Brand,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
3,ORD1004,Pooja Yadav,Monitor,Electronics,Dell,28721,3,Delhi,Delhi,24-01-2025,Pending,1.0,Good Product (Satisfied),Credit Card,86163
4,ORD1005,Arjun Mehta,Smart Watch,Electronics,Apple,6195,4,Pune,MH,01-02-2025,Pending,5.0,Good Product (Satisfied),Net Banking,24780
13,ORD1014,Nikita Rao,Headphone,Accessories,Sony,15514,5,Bhopal,MP,14-06-2025,Pending,3.0,Good Product (Satisfied),Credit Card,77570
14,ORD1015,Mohit Gupta,Keyboard,Accessories,Logitech,925,3,Hyderabad,TS,15-02-2025,Cancelled,5.0,Good Product (Satisfied),Credit Card,2775
29,ORD1030,Aman Verma,Smart Watch,Electronics,Apple,66409,5,Hyderabad,TS,15-01-2025,Cancelled,2.0,Good Product (Satisfied),Cash,332045
32,ORD1033,Pooja Yadav,Mouse,Accessories,Logitech,52376,2,Pune,MH,28-04-2025,Pending,3.0,Good Product (Satisfied),UPI,104752
45,ORD1046,Anjali Gupta,Smart Watch,Electronics,Apple,45809,3,Jaipur,RJ,05-06-2025,Cancelled,4.0,Good Product (Satisfied),Debit Card,137427
56,ORD1057,Nikita Rao,Mouse,Accessories,Logitech,68827,4,Pune,MH,12-03-2025,Pending,2.0,Good Product (Satisfied),Credit Card,275308
77,ORD1078,Harsh Agrawal,Tablet,Electronics,Apple,59973,3,Nagpur,MH,06-03-2025,Delivered,3.0,Good Product (Satisfied),Cash,179919
89,ORD1090,Priya Singh,Laptop,Electronics,HP,40819,5,Delhi,Delhi,15-03-2025,Pending,5.0,Good Product (Satisfied),Debit Card,204095
104,ORD1105,Neha Soni,Keyboard,Accessories,Logitech,5352,2,Hyderabad,TS,01-06-2025,Pending,5.0,Good Product (Satisfied),Debit Card,10704
105,ORD1106,Anjali Gupta,Headphone,Accessories,Sony,2511,2,Hyderabad,TS,17-06-2025,Delivered,4.0,Good Product (Satisfied),Debit Card,5022
107,ORD1108,Aman Verma,Smart Watch,Electronics,Apple,31271,3,Indore,MP,24-01-2025,Pending,2.0,Good Product (Satisfied),UPI,93813
120,ORD1121,Karan Shah,Speaker,Accessories,Boat,74084,3,Bhopal,MP,26-02-2025,Cancelled,5.0,Good Product (Satisfied),Debit Card,222252
129,ORD1130,Pooja Yadav,Laptop,Electronics,HP,35282,1,Delhi,Delhi,18-04-2025,Cancelled,2.0,Good Product (Satisfied),UPI,35282
143,ORD1144,Deepak Jain,Smart Watch,Electronics,Apple,7395,2,Indore,MP,08-06-2025,Delivered,2.0,Good Product (Satisfied),Credit Card,14790
144,ORD1145,Simran Kaur,Printer,Office,Canon,58439,4,Hyderabad,TS,25-02-2025,Cancelled,3.0,Good Product (Satisfied),Credit Card,233756
160,ORD1161,Neha Soni,Printer,Office,Canon,78866,1,Nagpur,MH,17-01-2025,Pending,3.0,Good Product (Satisfied),Net Banking,78866
164,ORD1165,Pooja Yadav,Speaker,Accessories,Boat,30193,2,Mumbai,MH,20-01-2025,Pending,2.0,Good Product (Satisfied),Net Banking,60386
170,ORD1171,Vivek Joshi,Mobile,Electronics,Samsung,36255,4,Delhi,Delhi,07-02-2025,Pending,5.0,Good Product (Satisfied),Cash,145020
173,ORD1174,Aman Verma,Monitor,Electronics,Dell,18691,4,Hyderabad,TS,07-06-2025,Delivered,4.0,Good Product (Satisfied),UPI,74764
175,ORD1176,Vivek Joshi,Mobile,Electronics,Samsung,31752,4,Bhopal,MP,28-04-2025,Delivered,5.0,Good Product (Satisfied),Debit Card,127008
177,ORD1178,Sakshi Sharma,Tablet,Electronics,Apple,75298,4,Mumbai,MH,20-06-2025,Cancelled,2.0,Good Product (Satisfied),Net Banking,301192
198,ORD1199,Vivek Joshi,Keyboard,Accessories,Logitech,42791,2,Delhi,Delhi,13-05-2025,Pending,3.0,Good Product (Satisfied),Credit Card,85582
199,ORD1200,Aditi Mishra,Headphone,Accessories,Sony,16906,3,Pune,MH,07-06-2025,Cancelled,0.0,Good Product (Satisfied),Net Banking,50718
202,ORD1203,Harsh Agrawal,Monitor,Electronics,Dell,63800,2,Pune,MH,18-03-2025,Pending,4.0,Good Product (Satisfied),UPI,127600
217,ORD1218,Riya Tiwari,Smart Watch,Electronics,Apple,19869,2,Jaipur,RJ,27-05-2025,Cancelled,1.0,Good Product (Satisfied),Cash,39738
223,ORD1224,Neha Soni,Printer,Office,Canon,19698,3,Nagpur,MH,15-03-2025,Cancelled,1.0,Good Product (Satisfied),Credit Card,59094
227,ORD1228,Akash Dubey,Speaker,Accessories,Boat,38149,3,Mumbai,MH,15-06-2025,Delivered,3.0,Good Product (Satisfied),Net Banking,114447
230,ORD1231,Harsh Agrawal,Headphone,Accessories,Sony,18089,5,Hyderabad,TS,11-03-2025,Delivered,4.0,Good Product (Satisfied),Credit Card,90445
232,ORD1233,Sakshi Sharma,Printer,Office,Canon,68038,3,Jaipur,RJ,13-04-2025,Cancelled,1.0,Good Product (Satisfied),Cash,204114
234,ORD1235,Pooja Yadav,Monitor,Electronics,Dell,34782,3,Bhopal,MP,16-01-2025,Cancelled,2.0,Good Product (Satisfied),Debit Card,104346
262,ORD1263,Rohit Patel,Headphone,Accessories,Sony,24623,5,Hyderabad,TS,15-05-2025,Delivered,1.0,Good Product (Satisfied),UPI,123115
276,ORD1277,Priya Singh,Monitor,Electronics,Dell,50307,2,Delhi,Delhi,23-03-2025,Pending,4.0,Good Product (Satisfied),UPI,100614
278,ORD1279,Simran Kaur,Headphone,Accessories,Sony,14038,1,Jaipur,RJ,01-04-2025,Cancelled,1.0,Good Product (Satisfied),Net Banking,14038
281,ORD1282,Rohit Patel,Mobile,Electronics,Samsung,57473,3,Delhi,Delhi,18-03-2025,Pending,4.0,Good Product (Satisfied),Credit Card,172419
292,ORD1293,Rohit Patel,Tablet,Electronics,Apple,63777,1,Bhopal,MP,17-04-2025,Delivered,3.0,Good Product (Satisfied),Cash,63777

## Q24. Remove extra spaces from Customer.

In [26]:
df['Customer'].str.strip()

0       Anjali Gupta
1        Deepak Jain
2      Harsh Agrawal
3        Pooja Yadav
4        Arjun Mehta
           ...
298    Harsh Agrawal
299      Pooja Yadav
300      Simran Kaur
301      Deepak Jain
302      Rohit Patel
Name: Customer, Length: 303, dtype: object

## Q25. Category-wise total sales.

In [27]:
df.groupby('Category')['Total_Amount'].sum()

Category
Accessories    15627647
Electronics    17974270
Office          3383852
Name: Total_Amount, dtype: int64

## Q26. Brand-wise average price.

In [28]:
df.groupby('Brand')['Price'].mean()

Brand
Apple       37738.984615
Boat        46371.892857
Canon       40052.914286
Dell        39726.032258
HP          39408.000000
Logitech    39297.841270
Samsung     49258.200000
Sony        37431.562500
Name: Price, dtype: float64

## Q27. Category-wise maximum price.

In [29]:
df.groupby('Category')["Price"].max()

Category
Accessories    79963
Electronics    79982
Office         78866
Name: Price, dtype: int64

## Q28. City-wise total quantity.

In [30]:
df.groupby('City')["Quantity"].sum()

City
Bhopal       112
Delhi        103
Hyderabad    122
Indore       106
Jaipur       136
Mumbai        84
Nagpur       111
Pune         121
Name: Quantity, dtype: int64

## Q29. Payment mode-wise average rating.

In [31]:
df.groupby('Payment_Mode')['Rating'].mean()

Payment_Mode
Cash           3.133333
Credit Card    3.046154
Debit Card     3.526316
Net Banking    2.745455
UPI            2.893939
Name: Rating, dtype: float64

## Q30. Count Delivery_Status.

In [32]:
df['Delivery_Status'].value_counts()

Delivery_Status
Cancelled    108
Pending      107
Delivered     88
Name: count, dtype: int64

## Q31. Count Category.

In [33]:
df['Category'].value_counts()

Category
Electronics    145
Accessories    123
Office          35
Name: count, dtype: int64

## Q32. Count Payment_Mode.

In [34]:
df['Payment_Mode'].value_counts()

Payment_Mode
UPI            66
Credit Card    65
Cash           60
Debit Card     57
Net Banking    55
Name: count, dtype: int64

## Q33. Top 5 highest sales.

In [35]:
df.sort_values(by='Total_Amount',ascending=False).head(5)

,Order_ID,Customer,Product,Category,Brand,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
213,ORD1214,Riya Tiwari,Speaker,Accessories,Boat,79963,5,Delhi,Delhi,25-03-2025,Cancelled,2.0,Bad Packaging (Delayed),Cash,399815
282,ORD1283,Nikita Rao,Mouse,Accessories,Logitech,78331,5,Hyderabad,TS,28-04-2025,Delivered,2.0,Average Quality (Late Delivery),Credit Card,391655
62,ORD1063,Harsh Agrawal,Laptop,Electronics,HP,78080,5,Jaipur,RJ,22-01-2025,Cancelled,1.0,Excellent (Must Buy),Cash,390400
216,ORD1217,Sakshi Sharma,Speaker,Accessories,Boat,76321,5,Pune,MH,14-01-2025,Cancelled,2.0,Nice Product (Value for Money),Cash,381605
249,ORD1250,Karan Shah,Smart Watch,Electronics,Apple,76190,5,Nagpur,MH,02-03-2025,Pending,3.0,Average Quality (Late Delivery),Net Banking,380950

## Q34. Bottom 5 sales.

In [36]:
df.sort_values(by='Total_Amount',ascending=False).tail(5)

,Order_ID,Customer,Product,Category,Brand,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
16,ORD1017,Sakshi Sharma,Tablet,Electronics,Apple,3052,1,Hyderabad,TS,20-03-2025,Delivered,3.0,Excellent Product (Fast Delivery),Cash,3052
146,ORD1147,Neha Soni,Smart Watch,Electronics,Apple,1507,2,Bhopal,MP,24-02-2025,Delivered,3.0,Worth Buying (Happy Customer),Credit Card,3014
14,ORD1015,Mohit Gupta,Keyboard,Accessories,Logitech,925,3,Hyderabad,TS,15-02-2025,Cancelled,5.0,Good Product (Satisfied),Credit Card,2775
101,ORD1102,Pooja Yadav,Headphone,Accessories,Sony,836,3,Pune,MH,31-05-2025,Cancelled,3.0,Nice Product (Value for Money),Cash,2508
20,ORD1021,Karan Shah,Smart Watch,Electronics,Apple,1442,1,Mumbai,MH,28-02-2025,Delivered,1.0,Excellent Product (Fast Delivery),Credit Card,1442

## Q35. Find duplicate rows.

In [37]:
df[df.duplicated()]

,Order_ID,Customer,Product,Category,Brand,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
300,ORD1011,Simran Kaur,Keyboard,Accessories,Logitech,18801,2,Pune,MH,18-05-2025,Pending,5.0,Amazing (5 Stars),Debit Card,37602
301,ORD1012,Deepak Jain,Printer,Office,Canon,29246,2,Nagpur,MH,07-05-2025,Delivered,5.0,Excellent Product (Fast Delivery),UPI,58492
302,ORD1013,Rohit Patel,Keyboard,Accessories,Logitech,78672,1,Jaipur,RJ,08-04-2025,Cancelled,4.0,Nice Product (Value for Money),Net Banking,78672

## Q36. Remove duplicate rows.

In [38]:
df = df.drop_duplicates()
df

,Order_ID,Customer,Product,Category,Brand,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
0,ORD1001,Anjali Gupta,Laptop,Electronics,HP,32598,2,Pune,MH,27-01-2025,Cancelled,2.0,Poor Quality (Returned),UPI,65196
1,ORD1002,Deepak Jain,Printer,Office,Canon,4405,1,Bhopal,MP,01-03-2025,Cancelled,2.0,Amazing (5 Stars),UPI,4405
2,ORD1003,Harsh Agrawal,Mouse,Accessories,Logitech,29393,4,Jaipur,RJ,13-03-2025,Delivered,5.0,Average Quality (Late Delivery),Debit Card,117572
3,ORD1004,Pooja Yadav,Monitor,Electronics,Dell,28721,3,Delhi,Delhi,24-01-2025,Pending,1.0,Good Product (Satisfied),Credit Card,86163
4,ORD1005,Arjun Mehta,Smart Watch,Electronics,Apple,6195,4,Pune,MH,01-02-2025,Pending,5.0,Good Product (Satisfied),Net Banking,24780
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,ORD1296,Sneha Jain,Mouse,Accessories,Logitech,72839,2,Delhi,Delhi,24-05-2025,Pending,3.0,Nice Product (Value for Money),Cash,145678
296,ORD1297,Neha Soni,Keyboard,Accessories,Logitech,57140,4,Delhi,Delhi,07-06-2025,Delivered,1.0,Nice Product (Value for Money),Net Banking,228560
297,ORD1298,Mohit Gupta,Printer,Office,Canon,28653,2,Bhopal,MP,30-06-2025,Delivered,3.0,Amazing (5 Stars),UPI,57306
298,ORD1299,Harsh Agrawal,Keyboard,Accessories,Logitech,43227,2,Nagpur,MH,30-01-2025,Pending,4.0,Nice Product (Value for Money),Net Banking,86454
299,ORD1300,Pooja Yadav,Smart Watch,Electronics,Apple,51951,5,Jaipur,RJ,31-03-2025,Pending,1.0,Nice Product (Value for Money),Net Banking,259755

In [39]:
df.duplicated().sum()

np.int64(0)

## Q37. Save cleaned data as `Cleaned_TechMart.csv`.

In [40]:
df.to_csv("Cleaned_TechMart.csv", index=False)